#priority level: 4th
server:
  port: 8044
  servlet:
    context-path: /sshop

spring:
  application:
    name: SSHOP_springboot_backend
  datasource:
    url: jdbc:postgresql://localhost:5433/sshop
    username: postgres
    password: 123456
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update #Hibernate ddl auto options: update, create, drop, create-drop, validate, none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        # dialect: org.hibernate.dialect.PostgreSQLDialect
        # jdbc.lob.non_contextual_creation: true #doestn't use sessions to persist effectively
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

sshop:
  jwt:
    secret-key: 1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij
  media:
    uri: file:///D:/.Project/kltn/SSHOP_media
